script: ./make-wizard.sh
branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  target_branch: released-wizard
  local_dir: ./tmp/